#Twas the Night Before
#MADLibs Game

holiday = input("Enter a Holiday: ")
noun1 = input("Enter a noun: ")
animal = input("Enter an animal: ")
pl_noun_thing1 = input("Enter a plural noun (thing): ")
famous_person = input("Enter a famous person: ")
pl_noun_thing2 = input("Enter a plural noun (thing): ")
fruit = input("Enter a fruit (plural): ")
verb = input("Enter a verb (past tense): ")
verb2 = input("Enter another verb (past tense): ")
adjective = input("Enter an adjective: ")
noun_place = input("Enter a noun (place): ")
verb3 = input("Enter a verb (past tense): ")
noun_place2 = input("Enter a noun (place): ")
noun2 = input("Enter a noun: ")
verb4 = input("Enter a verb (past tense): ")
verb5 = input("Enter a verb (past tense): ")
noun3 = input("Enter a noun: ")
noun4 = input("Enter another noun: ")
adjective2 = input ("Enter an adjective: ")
adjective3 = input ("Enter an adjective: ")
noun5 = input ("Enter a noun: ")
adjective4 = input("Enter an adjective: ")
noun_animal = input("Enter an animal (plural): ")

print("Twas the night before " + holiday + ", when all through the " + noun1 + ",")
print("Not a creature was stirring, not even a " + animal + ";")
print("The " + pl_noun_thing1 + " were hung by the chimney with care,")
print("In hopes that " + famous_person + " soon would be there;")
print("The children were nestled all snug in their " + pl_noun_thing2 + ",")
print("While visions of " + fruit + " " + verb + " in their heads;")
print("And mamma in her kerchief, and I in my cap,")
print("Had just " + verb2 + " our brains for a " + adjective + " winter's nap,")
print("When out on the " + noun_place + " there arose such a clatter,")
print("I " + verb3 + " from the " + noun_place2 + " to see what was the matter.")
print("Away to the " + noun2 + " I  " + verb4 + " like a flash,")
print( verb5 + " open the " + noun3 + " and threw up the sash.")
print("The " + noun4 + " on the breast of the " + adjective2 + " snow,")
print("Gave the luster of mid-day objects below,")
print("When, what to my " + adjective3 + " eyes should appear,")
print("But a miniature " + noun5 + ", and eight " + adjective4 + " " + noun_animal + ".")
